# Generated by Django 5.2.10 on 2026-01-22 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_code', models.CharField(max_length=10, unique=True)),
                ('duration', models.PositiveIntegerField(help_text='Duration from parent')),
                ('position', models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right')], max_length=5, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='routes.airport')),
            ],
            options={
                'verbose_name': 'Airport Route',
                'verbose_name_plural': 'Airport Routes',
            },
        ),
        migrations.DeleteModel(
            name='AirportRoute',
        ),
    ]
