# Generated by Django 5.2.10 on 2026-01-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_airport_delete_airportroute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='airport_code',
            field=models.CharField(max_length=10),
        ),
    ]
