# Generated by Django 5.2.10 on 2026-01-22 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_alter_airport_airport_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airport',
            options={},
        ),
    ]
